server:
  port: 8090
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=2
        - id: oauth-service
          uri: lb://oauth-service
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka